stages:
  - test
  - deploy

default:
  # Also change versions in Dockerfile
  image: hexpm/elixir:1.16.1-erlang-26.2.2-debian-bullseye-20240130-slim
  cache:
    paths:
      - deps/
      - _build/

before_script:
  # git for "master" branch version of phoenix
  - apk add make g++ git
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

format:
  stage: test
  script:
    - mix format --check-formatted
    - mix compile --warnings-as-errors

i18n:
  stage: test
  script:
    - mix gettext.extract --check-up-to-date

test:
  stage: test
  script:
    - mix test

deploy:
  stage: deploy
  cache: []
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy
