stages:
  - test
  - deploy

default:
  # Also change versions in Dockerfile
  image: hexpm/elixir:1.14.0-erlang-25.1.1-alpine-3.16.2
  cache:
    paths:
      - deps/
      - _build/

before_script:
  # git for "master" branch version of phoenix
  - apk add make g++ git
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

format:
  stage: test
  script:
    - mix format --check-formatted

i18n:
  stage: test
  script:
    - mix gettext.extract --check-up-to-date

test:
  stage: test
  services:
    - postgres:14.5-alpine
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - mix test

deploy:
  stage: deploy
  cache: []
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy
